/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Constants for main content area.
 */
export class ContentConstants {
  static readonly PLAY_ALL_MAX_LINES: number = 1;
  static readonly SINGER_FONT_REDUCE: number = 4;
  static readonly ALBUM_FONT_PLUS: number = 2;
  static readonly INTRODUCTION_FONT_REDUCE: number = 2;
  static readonly DIVIDER_STROKE_WIDTH: number = 0.5;
  static readonly ASPECT_RATIO_ALBUM_COVER: number = 1;
  static readonly LETTER_SPACING: number = 1;
  static readonly ALBUM_FONT_WEIGHT: number = 500;
  static readonly INTRODUCTION_FONT_WEIGHT: number = 400;
  static readonly COVER_OPTION_SPACE: number = 4;
  static readonly COL_TWO: number = 2;
  static readonly COL_ONE: number = 1;
}
