/*
 * PlayerConstants - 播放器常量
 */
export class PlayerConstants {
  public static readonly FONT_REDUCE: number = 4;
  public static readonly LAYOUT_WEIGHT_PLAYER_CONTROL: number = 1;
  public static readonly DISPLAY_PRIORITY_PLAYLIST_ENTRY: number = 1;
  public static readonly DISPLAY_PRIORITY_TRACK_SKIP: number = 2;
  public static readonly DISPLAY_PRIORITY_PLAY_PAUSE: number = 3;
  public static readonly ROTATE: number = 360;
  public static readonly ANIMATION_DURATION: number = 3000;
  public static readonly ITERATIONS: number = -1;
  public static readonly FONT_FAMILY_BLACK: string = 'HarmonyHeiTi';
  public static readonly FONT_FAMILY_BOLD: string = 'HarmonyHeiTi-Bold';
  public static readonly FONT_FAMILY_MEDIUM: string = 'HarmonyHeiTi-Medium';
  public static readonly ENCODING: string = 'utf-8';
  public static readonly BACK_IMAGE: string = '120%';
  public static readonly IMAGE_BLUR: number = 15;
}
